// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace Issen
{
	public class Damage
	{
		private int hp = 0;

		public Damage ()
		{
		}

		public Damage (int hp)
		{
			this.hp = hp;
		}

		public int Hp { get { return hp; } }

		public static Damage MinionToMinion(Minion attacker, Minion defender)
		{
			var hpDamage = Math.Max(attacker.Strength - defender.Armor, 0);
			return new Damage(hp: hpDamage);
		}

	}
}

