// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace Issen
{
	public class Enemy:Minion
	{
		public Enemy(int hp, int strength) : base(hp, strength) {}
		public Enemy() : base() {}

		public override void Think(Battle battle)
		{
			// NOTE: battleの履歴や対戦相手の情報から次の手を考える でも面倒なのでランダム
			DecideCard(new Random().Next(1, 10));
		}
	}
}

